### ISSUE TITLE
Gui/Term Colors

### ISSUE THREAD

**Issue by jbkopecky** [junegunn/vim-journal#2]
Hello Junegunn!

Thank you for this cool code !

I know you don't really want to be bothered about this plugin, but this is more a question than an issue report.

I have noticed that the indents highlighting were not working in my terminal, and after going through `syntax/journal.vim` ( I learned a lot reading it, thanks !) I noticed that it was because the statement has('gui') in the code was returning 1, even inside my terminal. When I modified: `has('gui')` into: `has("gui_running")` I could get working colored indents. (indent{n} highlighting group colors are then declared as cterm colors whereas before, they were declared as gui colors)

Do you have any idea why my vim would return 1 when I `echo has('gui')` inside my terminal vim? (No gvim instance running )

Thanks again !

**Comment by junegunn** [comment]
Ah, actually this seems like a bug. It should check `gui_running` instead of `gui`. (See `:h feature-list` for the details)

**Comment by junegunn** [comment]
Should be fixed now. Thanks for letting me know :)

**Comment by jbkopecky** [comment]
Awesome, it's working! Thanks ! ;)
