### ISSUE TITLE
Install instruction

### ISSUE THREAD

**Issue by aratno** [junegunn/vim-journal#5]
Hey junegunn,

I've been looking for a simple vim syntax for taking notes that properly indents multiline bullets, and this seems to be it. Only issue is, I'm not very familiar with the innards of vim and don't want to risk ruining my current environment by incorrectly installing it (as has happened to me in the past). Would you be able to put up some instructions?

Thanks,
Abe

**Comment by junegunn** [comment]
This is a personal plugin and I don't make any promises, so I intentionally left the documentation incomplete. But you can install it like any other plugins. Do you use a plugin manager? Take a look at [vim-plug](https://github.com/junegunn/vim-plug) if you don't use one.

Even when installed, the plugin is not activated by default. You'll have to `set ft=journal` manually, or automatically using `autocmd`s. There is [`g:journal#dirs` variable](https://github.com/junegunn/vim-journal/blob/d4b55c2336144ce26b925f333796bc06a658933c/ftdetect/journal.vim#L26-L29) but it's undocumented and may change in the future.

**Comment by aratno** [comment]
I just tried installing with vim-plug, and the installation seems to have worked. When I edit a `.md` file and type `:set ft=journal`, I get `E539: Illegal character <j>: formatoptions=tcroqnj1`. What am I doing wrong?

**Comment by junegunn** [comment]
`j` flag for `formatoptions` was added relatively recently, so you must be running an older version of Vim. I suggest that you upgrade Vim, but I can make the code ignore the error. By the way, I don't recommend using this for markdown files. The syntax is different.
