### ISSUE TITLE
vim-journal overrides my indentation defaults.

### ISSUE THREAD

**Issue by kingy9000** [junegunn/vim-journal#6]
vim-journal, a fantastic plugin, overrides my tab keys defaults. I prefer to have it output a regular tab character at the length of 4 spaces while vim-journal makes it output 2 regular spaces when I press the tab key.

I know I could comment line 24 in [ftplugin/journal.vim](https://github.com/junegunn/vim-journal/blob/master/ftplugin/journal.vim) but that prevents me from easily keeping the plugin up to date. 

I was hoping that a setting could be implemented upstream that would allow users to disable this indent replacement. Or if you know how I could change my .vimrc to prevent this from happening that would be great.

**Comment by junegunn** [comment]
Okay, it seems it makes sense to respect the user's settings. After all, I already have those settings in my vimrc. Removed the line.
